### ISSUE TITLE
It doesn't work with copying to the clipboard

### ISSUE THREAD

**Issue by parfeniukink** [alfredapp/shortcuts-workflow#1]
### Workflow version

latest

### Alfred version

2022.6

### macOS version

12.3.1

### Debugger output

```alfred_debugger
No output
```

### More details

For example lets create a simple workflow in Siri Shortcuts.

1.  Make a GIF from Clipboard (on this step you have a video copied to the clipboard)
2. Copy GIF to the Clipboard

<img width="848" alt="image" src="https://user-images.githubusercontent.com/45270625/167620273-2fa525d2-cc0b-4363-8c74-a06d6cbb5c5c.png">

In clipboard we have
![image](https://user-images.githubusercontent.com/45270625/167620230-9f5f3ee8-3baa-4491-9767-6a370185e0f5.gif)

**Comment by vitorgalvao** [comment]
> latest

Please never say “latest” but always the exact version. “Latest” is often wrong and makes it impossible for people who face the same issue later on to know if their version matches the report. An example of when it can be problematic: because you seem to be referring to Alfred’s version, it is impossible to know which version you’re referring to because there is currently a stable version and a pre-release—two versions which could be reasonably classified as “latest”.

Fortunately, it doesn’t matter in this case. The Workflow does work with copying to the clipboard, but only text content. Without getting bogged down in the details, the Workflow uses the clipboard to temporarily store information to get around [NSTask](https://developer.apple.com/documentation/foundation/nstask)’s decomposition.

I have changed the approach. Are you able to confirm [this new version](https://github.com/alfredapp/shortcuts-workflow/files/8662207/Shortcuts.alfredworkflow.zip) works for you?

**Comment by vitorgalvao** [comment]
[2022.7 is out](https://github.com/alfredapp/shortcuts-workflow/releases/tag/2022.7) with the change.
