### ISSUE TITLE
Quering takes time

### ISSUE THREAD

**Issue by alwinsamson** [alfredapp/shortcuts-workflow#10]
### Workflow version

v2024.1

### Alfred version

5.1.4

### macOS version

macOS Sonoma 14.3.1

### Debugger output

```alfred_debugger
[16:12:21.429] Shortcuts[Script Filter] Queuing argument '(null)'
[16:12:28.307] Shortcuts[Script Filter] Script with argv '(null)' finished
[16:12:28.312] Shortcuts[Script Filter] {"cache":{"seconds":300,"loosereload":true},"items":s
```

### More details

Previous updates were much snappier, didn't even have to wait for this long.

**Comment by vitorgalvao** [comment]
This is now using the new caching mechanism in [Alfred 5.5 Beta](https://www.alfredapp.com/whats-new/). You can update Alfred or [download the previous version](https://github.com/alfredapp/shortcuts-workflow/releases/tag/2023.8) in the meantime if you prefer.

**Comment by vitorgalvao** [comment]
You can’t be having the same issue, because the one above was based on the cache never being saved due to not having the correct Alfred version.

What you’ll be be seeing is [the cache being rebuilt more often](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/#cache) and in the foreground, while previously it was always in the background and done less often. You should only see a slower build after restarting Alfred and then they’re instant.
