### ISSUE TITLE
FR: Option to copy URL to run shortcut

### ISSUE THREAD

**Issue by csss1234** [alfredapp/shortcuts-workflow#4]
### Workflow version

v2022.12

### Alfred version

5.0.6

### macOS version

13.1

### Debugger output

```alfred_debugger
n/a
```

### More details

Would love ability to press a modifier key and copy url to run shortcut. Thanks for the workflow!

**Comment by vitorgalvao** [comment]
I’m not sure I understand the request. Are you trying to copy [the URL scheme](https://support.apple.com/en-gb/guide/shortcuts-mac/apda283236d7/mac)? Those are simple to write and I don’t see how copying them would be a common action. Can you expand on the use case?

**Comment by csss1234** [comment]
I'm probably a shortcuts "power user", I have a few hundred and use them constantly. I particularly like being able to trigger them from Obsidian notes, Calendar events, and Reminders. 

Example: On sunday I go through my weekly planning checklist in Obsidian. There are probably 7 shortcut urls linked in there, and I'm always making new ones and changing them. Because I have so many, I use long names, often with emoji. So creating the run-shortcut url is just a pain. I even have a shortcut to create a url for a shortcut! But. It's 10x slower than doing it through Alfred would be (it lists every shortcut for me to scroll though)

**Comment by vitorgalvao** [comment]
[This workflow](https://github.com/alfredapp/shortcuts-workflow/files/10564011/Shortcuts.alfredworkflow.zip) will do what you ask. Do <kbd>fn</kbd><kbd>↩&#xFE0E;</kbd> to copy the URL scheme. Since the request is quite niche I’m considering if it makes sense to make it an integral part of the official release. See those blue objects at the bottom? If you update the workflow, be sure to copy and readd them to the updated version, in case the feature doesn’t make it in to the next official release.

**Comment by csss1234** [comment]
> [This workflow](https://github.com/alfredapp/shortcuts-workflow/files/10564011/Shortcuts.alfredworkflow.zip) will do what you ask. Do fn↩︎ to copy the URL scheme. Since the request is quite niche I’m considering if it makes sense to make it an integral part of the official release. See those blue objects at the bottom? If you update the workflow, be sure to copy and readd them to the updated version, in case the feature doesn’t make it in to the next official release.

Wow thank you! 😃
